### ISSUE TITLE
код фикс

### ISSUE THREAD

**Issue by itskekoff** [Hiver13/Kreora#1]
ты долбаеб тупой нахуй
твой код нечитаем, не содержит английского языка в перемнных и впринципе он говно ебанное, вывод: ливай нахуй с комьюнити

**Comment by Hiver13** [comment]
много чего хочешь

**Comment by knwportale** [comment]
> ты долбаеб тупой нахуй твой код нечитаем, не содержит английского языка в перемнных и впринципе он говно ебанное, вывод: ливай нахуй с комьюнити

согласен

**Comment by IlyaYevtyhov** [comment]
+ в новых версиях ратк падкачиваиц
